// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: discovery.proto

package meshpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiscoveryRegistry_Register_FullMethodName     = "/toskamesh.discovery.DiscoveryRegistry/Register"
	DiscoveryRegistry_Deregister_FullMethodName   = "/toskamesh.discovery.DiscoveryRegistry/Deregister"
	DiscoveryRegistry_GetInstances_FullMethodName = "/toskamesh.discovery.DiscoveryRegistry/GetInstances"
	DiscoveryRegistry_GetServices_FullMethodName  = "/toskamesh.discovery.DiscoveryRegistry/GetServices"
	DiscoveryRegistry_ReportHealth_FullMethodName = "/toskamesh.discovery.DiscoveryRegistry/ReportHealth"
)

// DiscoveryRegistryClient is the client API for DiscoveryRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscoveryRegistryClient interface {
	Register(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*RegisterServiceResponse, error)
	Deregister(ctx context.Context, in *DeregisterServiceRequest, opts ...grpc.CallOption) (*DeregisterServiceResponse, error)
	GetInstances(ctx context.Context, in *GetInstancesRequest, opts ...grpc.CallOption) (*GetInstancesResponse, error)
	GetServices(ctx context.Context, in *GetServicesRequest, opts ...grpc.CallOption) (*GetServicesResponse, error)
	ReportHealth(ctx context.Context, in *ReportHealthRequest, opts ...grpc.CallOption) (*ReportHealthResponse, error)
}

type discoveryRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryRegistryClient(cc grpc.ClientConnInterface) DiscoveryRegistryClient {
	return &discoveryRegistryClient{cc}
}

func (c *discoveryRegistryClient) Register(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*RegisterServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterServiceResponse)
	err := c.cc.Invoke(ctx, DiscoveryRegistry_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryRegistryClient) Deregister(ctx context.Context, in *DeregisterServiceRequest, opts ...grpc.CallOption) (*DeregisterServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterServiceResponse)
	err := c.cc.Invoke(ctx, DiscoveryRegistry_Deregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryRegistryClient) GetInstances(ctx context.Context, in *GetInstancesRequest, opts ...grpc.CallOption) (*GetInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstancesResponse)
	err := c.cc.Invoke(ctx, DiscoveryRegistry_GetInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryRegistryClient) GetServices(ctx context.Context, in *GetServicesRequest, opts ...grpc.CallOption) (*GetServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServicesResponse)
	err := c.cc.Invoke(ctx, DiscoveryRegistry_GetServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryRegistryClient) ReportHealth(ctx context.Context, in *ReportHealthRequest, opts ...grpc.CallOption) (*ReportHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportHealthResponse)
	err := c.cc.Invoke(ctx, DiscoveryRegistry_ReportHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoveryRegistryServer is the server API for DiscoveryRegistry service.
// All implementations must embed UnimplementedDiscoveryRegistryServer
// for forward compatibility.
type DiscoveryRegistryServer interface {
	Register(context.Context, *RegisterServiceRequest) (*RegisterServiceResponse, error)
	Deregister(context.Context, *DeregisterServiceRequest) (*DeregisterServiceResponse, error)
	GetInstances(context.Context, *GetInstancesRequest) (*GetInstancesResponse, error)
	GetServices(context.Context, *GetServicesRequest) (*GetServicesResponse, error)
	ReportHealth(context.Context, *ReportHealthRequest) (*ReportHealthResponse, error)
	mustEmbedUnimplementedDiscoveryRegistryServer()
}

// UnimplementedDiscoveryRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscoveryRegistryServer struct{}

func (UnimplementedDiscoveryRegistryServer) Register(context.Context, *RegisterServiceRequest) (*RegisterServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedDiscoveryRegistryServer) Deregister(context.Context, *DeregisterServiceRequest) (*DeregisterServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deregister not implemented")
}
func (UnimplementedDiscoveryRegistryServer) GetInstances(context.Context, *GetInstancesRequest) (*GetInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstances not implemented")
}
func (UnimplementedDiscoveryRegistryServer) GetServices(context.Context, *GetServicesRequest) (*GetServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServices not implemented")
}
func (UnimplementedDiscoveryRegistryServer) ReportHealth(context.Context, *ReportHealthRequest) (*ReportHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportHealth not implemented")
}
func (UnimplementedDiscoveryRegistryServer) mustEmbedUnimplementedDiscoveryRegistryServer() {}
func (UnimplementedDiscoveryRegistryServer) testEmbeddedByValue()                           {}

// UnsafeDiscoveryRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryRegistryServer will
// result in compilation errors.
type UnsafeDiscoveryRegistryServer interface {
	mustEmbedUnimplementedDiscoveryRegistryServer()
}

func RegisterDiscoveryRegistryServer(s grpc.ServiceRegistrar, srv DiscoveryRegistryServer) {
	// If the following call panics, it indicates UnimplementedDiscoveryRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiscoveryRegistry_ServiceDesc, srv)
}

func _DiscoveryRegistry_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryRegistryServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryRegistry_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryRegistryServer).Register(ctx, req.(*RegisterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryRegistry_Deregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryRegistryServer).Deregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryRegistry_Deregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryRegistryServer).Deregister(ctx, req.(*DeregisterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryRegistry_GetInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryRegistryServer).GetInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryRegistry_GetInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryRegistryServer).GetInstances(ctx, req.(*GetInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryRegistry_GetServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryRegistryServer).GetServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryRegistry_GetServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryRegistryServer).GetServices(ctx, req.(*GetServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryRegistry_ReportHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryRegistryServer).ReportHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryRegistry_ReportHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryRegistryServer).ReportHealth(ctx, req.(*ReportHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscoveryRegistry_ServiceDesc is the grpc.ServiceDesc for DiscoveryRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscoveryRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "toskamesh.discovery.DiscoveryRegistry",
	HandlerType: (*DiscoveryRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _DiscoveryRegistry_Register_Handler,
		},
		{
			MethodName: "Deregister",
			Handler:    _DiscoveryRegistry_Deregister_Handler,
		},
		{
			MethodName: "GetInstances",
			Handler:    _DiscoveryRegistry_GetInstances_Handler,
		},
		{
			MethodName: "GetServices",
			Handler:    _DiscoveryRegistry_GetServices_Handler,
		},
		{
			MethodName: "ReportHealth",
			Handler:    _DiscoveryRegistry_ReportHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discovery.proto",
}
