// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: discovery.proto

package meshpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNKNOWN   HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY   HealthStatus = 1
	HealthStatus_HEALTH_STATUS_UNHEALTHY HealthStatus = 2
	HealthStatus_HEALTH_STATUS_DEGRADED  HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNKNOWN",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_UNHEALTHY",
		3: "HEALTH_STATUS_DEGRADED",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNKNOWN":   0,
		"HEALTH_STATUS_HEALTHY":   1,
		"HEALTH_STATUS_UNHEALTHY": 2,
		"HEALTH_STATUS_DEGRADED":  3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_discovery_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_discovery_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{0}
}

type HealthCheckConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Endpoint           string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	IntervalSeconds    int32                  `protobuf:"varint,2,opt,name=intervalSeconds,proto3" json:"intervalSeconds,omitempty"`
	TimeoutSeconds     int32                  `protobuf:"varint,3,opt,name=timeoutSeconds,proto3" json:"timeoutSeconds,omitempty"`
	UnhealthyThreshold int32                  `protobuf:"varint,4,opt,name=unhealthyThreshold,proto3" json:"unhealthyThreshold,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HealthCheckConfig) Reset() {
	*x = HealthCheckConfig{}
	mi := &file_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckConfig) ProtoMessage() {}

func (x *HealthCheckConfig) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckConfig.ProtoReflect.Descriptor instead.
func (*HealthCheckConfig) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *HealthCheckConfig) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *HealthCheckConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *HealthCheckConfig) GetUnhealthyThreshold() int32 {
	if x != nil {
		return x.UnhealthyThreshold
	}
	return 0
}

type RegisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HealthCheck   *HealthCheckConfig     `protobuf:"bytes,6,opt,name=healthCheck,proto3" json:"healthCheck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceRequest) Reset() {
	*x = RegisterServiceRequest{}
	mi := &file_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceRequest) ProtoMessage() {}

func (x *RegisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceRequest.ProtoReflect.Descriptor instead.
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegisterServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RegisterServiceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterServiceRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegisterServiceRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterServiceRequest) GetHealthCheck() *HealthCheckConfig {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

type RegisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceResponse) Reset() {
	*x = RegisterServiceResponse{}
	mi := &file_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceResponse) ProtoMessage() {}

func (x *RegisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceResponse.ProtoReflect.Descriptor instead.
func (*RegisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterServiceResponse) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RegisterServiceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DeregisterServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterServiceRequest) Reset() {
	*x = DeregisterServiceRequest{}
	mi := &file_discovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterServiceRequest) ProtoMessage() {}

func (x *DeregisterServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterServiceRequest.ProtoReflect.Descriptor instead.
func (*DeregisterServiceRequest) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{3}
}

func (x *DeregisterServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type DeregisterServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       bool                   `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterServiceResponse) Reset() {
	*x = DeregisterServiceResponse{}
	mi := &file_discovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterServiceResponse) ProtoMessage() {}

func (x *DeregisterServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterServiceResponse.ProtoReflect.Descriptor instead.
func (*DeregisterServiceResponse) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{4}
}

func (x *DeregisterServiceResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type GetInstancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstancesRequest) Reset() {
	*x = GetInstancesRequest{}
	mi := &file_discovery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstancesRequest) ProtoMessage() {}

func (x *GetInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstancesRequest.ProtoReflect.Descriptor instead.
func (*GetInstancesRequest) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{5}
}

func (x *GetInstancesRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type GetInstancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*ServiceInstance     `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstancesResponse) Reset() {
	*x = GetInstancesResponse{}
	mi := &file_discovery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstancesResponse) ProtoMessage() {}

func (x *GetInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstancesResponse.ProtoReflect.Descriptor instead.
func (*GetInstancesResponse) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{6}
}

func (x *GetInstancesResponse) GetInstances() []*ServiceInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type ServiceInstance struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceName     string                 `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	ServiceId       string                 `protobuf:"bytes,2,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	Address         string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Port            int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Status          HealthStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=toskamesh.discovery.HealthStatus" json:"status,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RegisteredAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=registeredAt,proto3" json:"registeredAt,omitempty"`
	LastHealthCheck *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=lastHealthCheck,proto3" json:"lastHealthCheck,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceInstance) Reset() {
	*x = ServiceInstance{}
	mi := &file_discovery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInstance) ProtoMessage() {}

func (x *ServiceInstance) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInstance.ProtoReflect.Descriptor instead.
func (*ServiceInstance) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceInstance) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceInstance) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceInstance) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServiceInstance) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceInstance) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNKNOWN
}

func (x *ServiceInstance) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ServiceInstance) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *ServiceInstance) GetLastHealthCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHealthCheck
	}
	return nil
}

type GetServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServicesRequest) Reset() {
	*x = GetServicesRequest{}
	mi := &file_discovery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServicesRequest) ProtoMessage() {}

func (x *GetServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServicesRequest.ProtoReflect.Descriptor instead.
func (*GetServicesRequest) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{8}
}

type GetServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceNames  []string               `protobuf:"bytes,1,rep,name=serviceNames,proto3" json:"serviceNames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServicesResponse) Reset() {
	*x = GetServicesResponse{}
	mi := &file_discovery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServicesResponse) ProtoMessage() {}

func (x *GetServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServicesResponse.ProtoReflect.Descriptor instead.
func (*GetServicesResponse) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{9}
}

func (x *GetServicesResponse) GetServiceNames() []string {
	if x != nil {
		return x.ServiceNames
	}
	return nil
}

type ReportHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	Status        HealthStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=toskamesh.discovery.HealthStatus" json:"status,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportHealthRequest) Reset() {
	*x = ReportHealthRequest{}
	mi := &file_discovery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportHealthRequest) ProtoMessage() {}

func (x *ReportHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportHealthRequest.ProtoReflect.Descriptor instead.
func (*ReportHealthRequest) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{10}
}

func (x *ReportHealthRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ReportHealthRequest) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNKNOWN
}

func (x *ReportHealthRequest) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type ReportHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportHealthResponse) Reset() {
	*x = ReportHealthResponse{}
	mi := &file_discovery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportHealthResponse) ProtoMessage() {}

func (x *ReportHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportHealthResponse.ProtoReflect.Descriptor instead.
func (*ReportHealthResponse) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{11}
}

func (x *ReportHealthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_discovery_proto protoreflect.FileDescriptor

const file_discovery_proto_rawDesc = "" +
	"\n" +
	"\x0fdiscovery.proto\x12\x13toskamesh.discovery\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x01\n" +
	"\x11HealthCheckConfig\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12(\n" +
	"\x0fintervalSeconds\x18\x02 \x01(\x05R\x0fintervalSeconds\x12&\n" +
	"\x0etimeoutSeconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\x12.\n" +
	"\x12unhealthyThreshold\x18\x04 \x01(\x05R\x12unhealthyThreshold\"\xe4\x02\n" +
	"\x16RegisterServiceRequest\x12 \n" +
	"\vserviceName\x18\x01 \x01(\tR\vserviceName\x12\x1c\n" +
	"\tserviceId\x18\x02 \x01(\tR\tserviceId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12U\n" +
	"\bmetadata\x18\x05 \x03(\v29.toskamesh.discovery.RegisterServiceRequest.MetadataEntryR\bmetadata\x12H\n" +
	"\vhealthCheck\x18\x06 \x01(\v2&.toskamesh.discovery.HealthCheckConfigR\vhealthCheck\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"u\n" +
	"\x17RegisterServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1c\n" +
	"\tserviceId\x18\x02 \x01(\tR\tserviceId\x12\"\n" +
	"\ferrorMessage\x18\x03 \x01(\tR\ferrorMessage\"8\n" +
	"\x18DeregisterServiceRequest\x12\x1c\n" +
	"\tserviceId\x18\x01 \x01(\tR\tserviceId\"5\n" +
	"\x19DeregisterServiceResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\"7\n" +
	"\x13GetInstancesRequest\x12 \n" +
	"\vserviceName\x18\x01 \x01(\tR\vserviceName\"Z\n" +
	"\x14GetInstancesResponse\x12B\n" +
	"\tinstances\x18\x01 \x03(\v2$.toskamesh.discovery.ServiceInstanceR\tinstances\"\xcd\x03\n" +
	"\x0fServiceInstance\x12 \n" +
	"\vserviceName\x18\x01 \x01(\tR\vserviceName\x12\x1c\n" +
	"\tserviceId\x18\x02 \x01(\tR\tserviceId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x129\n" +
	"\x06status\x18\x05 \x01(\x0e2!.toskamesh.discovery.HealthStatusR\x06status\x12N\n" +
	"\bmetadata\x18\x06 \x03(\v22.toskamesh.discovery.ServiceInstance.MetadataEntryR\bmetadata\x12>\n" +
	"\fregisteredAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x12D\n" +
	"\x0flastHealthCheck\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0flastHealthCheck\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x14\n" +
	"\x12GetServicesRequest\"9\n" +
	"\x13GetServicesResponse\x12\"\n" +
	"\fserviceNames\x18\x01 \x03(\tR\fserviceNames\"\x86\x01\n" +
	"\x13ReportHealthRequest\x12\x1c\n" +
	"\tserviceId\x18\x01 \x01(\tR\tserviceId\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.toskamesh.discovery.HealthStatusR\x06status\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\"0\n" +
	"\x14ReportHealthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*}\n" +
	"\fHealthStatus\x12\x19\n" +
	"\x15HEALTH_STATUS_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x02\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x032\x93\x04\n" +
	"\x11DiscoveryRegistry\x12e\n" +
	"\bRegister\x12+.toskamesh.discovery.RegisterServiceRequest\x1a,.toskamesh.discovery.RegisterServiceResponse\x12k\n" +
	"\n" +
	"Deregister\x12-.toskamesh.discovery.DeregisterServiceRequest\x1a..toskamesh.discovery.DeregisterServiceResponse\x12c\n" +
	"\fGetInstances\x12(.toskamesh.discovery.GetInstancesRequest\x1a).toskamesh.discovery.GetInstancesResponse\x12`\n" +
	"\vGetServices\x12'.toskamesh.discovery.GetServicesRequest\x1a(.toskamesh.discovery.GetServicesResponse\x12c\n" +
	"\fReportHealth\x12(.toskamesh.discovery.ReportHealthRequest\x1a).toskamesh.discovery.ReportHealthResponseBHZ+github.com/toska-mesh/toska-mesh/pkg/meshpb\xaa\x02\x18ToskaMesh.Grpc.Discoveryb\x06proto3"

var (
	file_discovery_proto_rawDescOnce sync.Once
	file_discovery_proto_rawDescData []byte
)

func file_discovery_proto_rawDescGZIP() []byte {
	file_discovery_proto_rawDescOnce.Do(func() {
		file_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discovery_proto_rawDesc), len(file_discovery_proto_rawDesc)))
	})
	return file_discovery_proto_rawDescData
}

var file_discovery_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_discovery_proto_goTypes = []any{
	(HealthStatus)(0),                 // 0: toskamesh.discovery.HealthStatus
	(*HealthCheckConfig)(nil),         // 1: toskamesh.discovery.HealthCheckConfig
	(*RegisterServiceRequest)(nil),    // 2: toskamesh.discovery.RegisterServiceRequest
	(*RegisterServiceResponse)(nil),   // 3: toskamesh.discovery.RegisterServiceResponse
	(*DeregisterServiceRequest)(nil),  // 4: toskamesh.discovery.DeregisterServiceRequest
	(*DeregisterServiceResponse)(nil), // 5: toskamesh.discovery.DeregisterServiceResponse
	(*GetInstancesRequest)(nil),       // 6: toskamesh.discovery.GetInstancesRequest
	(*GetInstancesResponse)(nil),      // 7: toskamesh.discovery.GetInstancesResponse
	(*ServiceInstance)(nil),           // 8: toskamesh.discovery.ServiceInstance
	(*GetServicesRequest)(nil),        // 9: toskamesh.discovery.GetServicesRequest
	(*GetServicesResponse)(nil),       // 10: toskamesh.discovery.GetServicesResponse
	(*ReportHealthRequest)(nil),       // 11: toskamesh.discovery.ReportHealthRequest
	(*ReportHealthResponse)(nil),      // 12: toskamesh.discovery.ReportHealthResponse
	nil,                               // 13: toskamesh.discovery.RegisterServiceRequest.MetadataEntry
	nil,                               // 14: toskamesh.discovery.ServiceInstance.MetadataEntry
	(*timestamppb.Timestamp)(nil),     // 15: google.protobuf.Timestamp
}
var file_discovery_proto_depIdxs = []int32{
	13, // 0: toskamesh.discovery.RegisterServiceRequest.metadata:type_name -> toskamesh.discovery.RegisterServiceRequest.MetadataEntry
	1,  // 1: toskamesh.discovery.RegisterServiceRequest.healthCheck:type_name -> toskamesh.discovery.HealthCheckConfig
	8,  // 2: toskamesh.discovery.GetInstancesResponse.instances:type_name -> toskamesh.discovery.ServiceInstance
	0,  // 3: toskamesh.discovery.ServiceInstance.status:type_name -> toskamesh.discovery.HealthStatus
	14, // 4: toskamesh.discovery.ServiceInstance.metadata:type_name -> toskamesh.discovery.ServiceInstance.MetadataEntry
	15, // 5: toskamesh.discovery.ServiceInstance.registeredAt:type_name -> google.protobuf.Timestamp
	15, // 6: toskamesh.discovery.ServiceInstance.lastHealthCheck:type_name -> google.protobuf.Timestamp
	0,  // 7: toskamesh.discovery.ReportHealthRequest.status:type_name -> toskamesh.discovery.HealthStatus
	2,  // 8: toskamesh.discovery.DiscoveryRegistry.Register:input_type -> toskamesh.discovery.RegisterServiceRequest
	4,  // 9: toskamesh.discovery.DiscoveryRegistry.Deregister:input_type -> toskamesh.discovery.DeregisterServiceRequest
	6,  // 10: toskamesh.discovery.DiscoveryRegistry.GetInstances:input_type -> toskamesh.discovery.GetInstancesRequest
	9,  // 11: toskamesh.discovery.DiscoveryRegistry.GetServices:input_type -> toskamesh.discovery.GetServicesRequest
	11, // 12: toskamesh.discovery.DiscoveryRegistry.ReportHealth:input_type -> toskamesh.discovery.ReportHealthRequest
	3,  // 13: toskamesh.discovery.DiscoveryRegistry.Register:output_type -> toskamesh.discovery.RegisterServiceResponse
	5,  // 14: toskamesh.discovery.DiscoveryRegistry.Deregister:output_type -> toskamesh.discovery.DeregisterServiceResponse
	7,  // 15: toskamesh.discovery.DiscoveryRegistry.GetInstances:output_type -> toskamesh.discovery.GetInstancesResponse
	10, // 16: toskamesh.discovery.DiscoveryRegistry.GetServices:output_type -> toskamesh.discovery.GetServicesResponse
	12, // 17: toskamesh.discovery.DiscoveryRegistry.ReportHealth:output_type -> toskamesh.discovery.ReportHealthResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_discovery_proto_init() }
func file_discovery_proto_init() {
	if File_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discovery_proto_rawDesc), len(file_discovery_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discovery_proto_goTypes,
		DependencyIndexes: file_discovery_proto_depIdxs,
		EnumInfos:         file_discovery_proto_enumTypes,
		MessageInfos:      file_discovery_proto_msgTypes,
	}.Build()
	File_discovery_proto = out.File
	file_discovery_proto_goTypes = nil
	file_discovery_proto_depIdxs = nil
}
